# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:14

# Create and change to the app directory.
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Set environment variables
ENV GOOGLE_CLIENT_ID=3649938618-lif15qu37cggb3li34cupkjnchehqh6s.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SECRET=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
ENV MONGO_URI=mongodb+srv://wandrilledioubate:T9cJLCjmnAexcYFw@inventory-app.ca1jaqt.mongodb.net/IMS?retryWrites=true&w=majority&appName=inventory-app
ENV PORT=3001
ENV SECRET_KEY=wandrille
ENV FRONTEND_URL=https://front-end-zbgxc2hu5q-no.a.run.app
ENV BACKEND_URL=https://back-end-zbgxc2hu5q-no.a.run.app

# Run the app
CMD [ "node", "index.js" ]
