# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:14

# Create and change to the app directory.
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Set environment variables
ENV GOOGLE_CLIENT_ID=
ENV GOOGLE_CLIENT_SECRET=
ENV MONGO_URI=
ENV PORT=
ENV SECRET_KEY=
ENV FRONTEND_URL=
ENV BACKEND_URL=

# Run the app
CMD [ "node", "index.js" ]
